# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.03) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/africa.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Africa::Asmera;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Africa::Asmera::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '58980000268',
    'utc_start' => DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '58980009600',
    'is_dst' => 0,
    'offset' => 9332,
    'local_start' => DateTime::TimeZone::NEG_INFINITY
  },
  {
    'short_name' => 'AMT',
    'utc_end' => '59611152268',
    'utc_start' => '58980000268',
    'local_end' => '59611161600',
    'is_dst' => 0,
    'offset' => 9332,
    'local_start' => '58980009600'
  },
  {
    'short_name' => 'ADMT',
    'utc_end' => '61073472280',
    'utc_start' => '59611152268',
    'local_end' => '61073481600',
    'is_dst' => 0,
    'offset' => 9320,
    'local_start' => '59611161588'
  },
  {
    'short_name' => 'EAT',
    'utc_end' => DateTime::TimeZone::INFINITY,
    'utc_start' => '61073472280',
    'local_end' => DateTime::TimeZone::INFINITY,
    'offset' => 10800,
    'local_start' => '61073461480'
  }
]
;

my $max_year = 2013;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

