# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.06) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/africa.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Africa::Johannesburg;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Africa::Johannesburg::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY,
59677510080,
DateTime::TimeZone::NEG_INFINITY,
59677516800,
6720,
0,
'LMT'
    ],
    [
59677510080,
60026394600,
59677515480,
60026400000,
5400,
0,
'SAST'
    ],
    [
60026394600,
61274707200,
60026401800,
61274714400,
7200,
0,
'SAST'
    ],
    [
61274707200,
61290428400,
61274718000,
61290439200,
10800,
1,
'SAST'
    ],
    [
61290428400,
DateTime::TimeZone::INFINITY,
61290421200,
DateTime::TimeZone::INFINITY,
7200,
0,
'SAST'
    ],
];

sub _max_year { 2013 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

