# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.06) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/africa.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Africa::Tunis;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Africa::Tunis::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY,
59338480756,
DateTime::TimeZone::NEG_INFINITY,
59338483200,
2444,
0,
'LMT'
    ],
    [
59338480756,
60279724239,
59338481317,
60279724800,
561,
0,
'PMT'
    ],
    [
60279724239,
61323181200,
60279727839,
61323184800,
3600,
0,
'CET'
    ],
    [
61323181200,
62726824800,
61323188400,
62726832000,
7200,
1,
'CEST'
    ],
    [
62726824800,
62758278000,
62726828400,
62758281600,
3600,
0,
'CET'
    ],
    [
62758278000,
DateTime::TimeZone::INFINITY,
62758274400,
DateTime::TimeZone::INFINITY,
3600,
0,
'CET'
    ],
];

sub _max_year { 2013 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

