# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.04) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/northamerica.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Pacific::Honolulu;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Pacific::Honolulu::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59926775486',
    'utc_start' => DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59926737600',
    'is_dst' => 0,
    'offset' => -37886,
    'local_start' => DateTime::TimeZone::NEG_INFINITY
  },
  {
    'short_name' => 'HST',
    'utc_end' => '60978400200',
    'utc_start' => '59926775486',
    'local_end' => '60978362400',
    'is_dst' => 0,
    'offset' => -37800,
    'local_start' => '59926737686'
  },
  {
    'short_name' => 'HDT',
    'utc_end' => '60980211000',
    'utc_start' => '60978400200',
    'local_end' => '60980176800',
    'is_dst' => 0,
    'offset' => -34200,
    'local_start' => '60978366000'
  },
  {
    'short_name' => 'HT',
    'utc_end' => '61255485000',
    'utc_start' => '60980211000',
    'local_end' => '61255447200',
    'is_dst' => 0,
    'offset' => -37800,
    'local_start' => '60980173200'
  },
  {
    'short_name' => 'HWT',
    'utc_end' => '61366321800',
    'utc_start' => '61255485000',
    'local_end' => '61366287600',
    'is_dst' => 1,
    'offset' => -34200,
    'local_start' => '61255450800'
  },
  {
    'short_name' => 'HPT',
    'utc_end' => '61370307000',
    'utc_start' => '61366321800',
    'local_end' => '61370272800',
    'is_dst' => 1,
    'offset' => -34200,
    'local_start' => '61366287600'
  },
  {
    'short_name' => 'HST',
    'utc_end' => '61423533000',
    'utc_start' => '61370307000',
    'local_end' => '61423495200',
    'is_dst' => 0,
    'offset' => -37800,
    'local_start' => '61370269200'
  },
  {
    'short_name' => 'HST',
    'utc_end' => DateTime::TimeZone::INFINITY,
    'utc_start' => '61423533000',
    'local_end' => DateTime::TimeZone::INFINITY,
    'offset' => -36000,
    'local_start' => '61423569000'
  }
]
;

my $max_year = 2013;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

