# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.01) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from Tarawa.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Pacific::Tarawa;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Pacific::Tarawa::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59958188876',
    'utc_start' => $DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59958230400',
    'offset' => 41524,
    'local_start' => '-inf'
  },
  {
    'short_name' => 'GILT',
    'utc_end' => $DateTime::TimeZone::INFINITY,
    'utc_start' => '59958188876',
    'offset' => 43200
  }
]
;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

