# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.05) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/australasia.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Pacific::Yap;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Pacific::Yap::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59958197248',
    'utc_start' => DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59958230400',
    'is_dst' => 0,
    'offset' => 33152,
    'local_start' => DateTime::TimeZone::NEG_INFINITY
  },
  {
    'short_name' => 'YAPT',
    'utc_end' => '62127702000',
    'utc_start' => '59958197248',
    'local_end' => '62127734400',
    'is_dst' => 0,
    'offset' => 32400,
    'local_start' => '59958229648'
  },
  {
    'short_name' => 'YAPT',
    'utc_end' => DateTime::TimeZone::INFINITY,
    'utc_start' => '62127702000',
    'local_end' => DateTime::TimeZone::INFINITY,
    'offset' => 36000,
    'local_start' => '62127666000'
  }
]
;

my $max_year = 2013;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

