# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.01) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from Calcutta.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Asia::Calcutta;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Asia::Calcutta::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59295521192',
    'utc_start' => $DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59295542400',
    'offset' => 21208,
    'local_start' => '-inf'
  },
  {
    'short_name' => 'HMT',
    'utc_end' => '61244100400',
    'utc_start' => '59295521192',
    'local_end' => '61244121600',
    'offset' => 21200,
    'local_start' => '59295542392'
  },
  {
    'short_name' => 'BURT',
    'utc_end' => '61263624600',
    'utc_start' => '61244100400',
    'local_end' => '61263648000',
    'offset' => 23400,
    'local_start' => '61244123800'
  },
  {
    'short_name' => 'IST',
    'utc_end' => '61273045800',
    'utc_start' => '61263624600',
    'local_end' => '61273065600',
    'offset' => 19800,
    'local_start' => '61263644400'
  },
  {
    'short_name' => 'IST',
    'utc_end' => '61371538200',
    'utc_start' => '61273045800',
    'local_end' => '61371561600',
    'offset' => 23400,
    'local_start' => '61273069200'
  },
  {
    'short_name' => 'IST',
    'utc_end' => $DateTime::TimeZone::INFINITY,
    'utc_start' => '61371538200',
    'offset' => 19800
  }
]
;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

