# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.01) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from Pyongyang.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Asia::Pyongyang;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Asia::Pyongyang::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59611131420',
    'utc_start' => $DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59611161600',
    'is_dst' => 0,
    'offset' => 30180,
    'local_start' => '-inf'
  },
  {
    'short_name' => 'KST',
    'utc_end' => '60081751800',
    'utc_start' => '59611131420',
    'local_end' => '60081782400',
    'is_dst' => 0,
    'offset' => 30600,
    'local_start' => '59611162020'
  },
  {
    'short_name' => 'KST',
    'utc_end' => '60810188400',
    'utc_start' => '60081751800',
    'local_end' => '60810220800',
    'is_dst' => 0,
    'offset' => 32400,
    'local_start' => '60081784200'
  },
  {
    'short_name' => 'KST',
    'utc_end' => '60936420600',
    'utc_start' => '60810188400',
    'local_end' => '60936451200',
    'is_dst' => 0,
    'offset' => 30600,
    'local_start' => '60810219000'
  },
  {
    'short_name' => 'KST',
    'utc_end' => '61637554800',
    'utc_start' => '60936420600',
    'local_end' => '61637587200',
    'is_dst' => 0,
    'offset' => 32400,
    'local_start' => '60936453000'
  },
  {
    'short_name' => 'KST',
    'utc_end' => '61870752000',
    'utc_start' => '61637554800',
    'local_end' => '61870780800',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '61637583600'
  },
  {
    'short_name' => 'KST',
    'utc_end' => $DateTime::TimeZone::INFINITY,
    'utc_start' => '61870752000',
    'offset' => 32400
  }
]
;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

