# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.01) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from Ulaanbaatar.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Asia::Ulaanbaatar;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Asia::Ulaanbaatar::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '60102751948',
    'utc_start' => $DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '60102777600',
    'offset' => 25652,
    'local_start' => '-inf'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62388118800',
    'utc_start' => '60102751948',
    'local_end' => '62388144000',
    'offset' => 25200,
    'local_start' => '60102777148'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62553657600',
    'utc_start' => '62388118800',
    'local_end' => '62553686400',
    'offset' => 28800,
    'local_start' => '62388147600'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62601008400',
    'utc_start' => '62553657600',
    'local_end' => '62601040800',
    'offset' => 32400,
    'local_start' => '62553690000'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62616736800',
    'utc_start' => '62601008400',
    'local_end' => '62616765600',
    'offset' => 28800,
    'local_start' => '62601037200'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62632458000',
    'utc_start' => '62616736800',
    'local_end' => '62632490400',
    'offset' => 32400,
    'local_start' => '62616769200'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62648186400',
    'utc_start' => '62632458000',
    'local_end' => '62648215200',
    'offset' => 28800,
    'local_start' => '62632486800'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62663907600',
    'utc_start' => '62648186400',
    'local_end' => '62663940000',
    'offset' => 32400,
    'local_start' => '62648218800'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62679636000',
    'utc_start' => '62663907600',
    'local_end' => '62679664800',
    'offset' => 28800,
    'local_start' => '62663936400'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62695357200',
    'utc_start' => '62679636000',
    'local_end' => '62695389600',
    'offset' => 32400,
    'local_start' => '62679668400'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62711085600',
    'utc_start' => '62695357200',
    'local_end' => '62711114400',
    'offset' => 28800,
    'local_start' => '62695386000'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62726806800',
    'utc_start' => '62711085600',
    'local_end' => '62726839200',
    'offset' => 32400,
    'local_start' => '62711118000'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62742535200',
    'utc_start' => '62726806800',
    'local_end' => '62742564000',
    'offset' => 28800,
    'local_start' => '62726835600'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62758256400',
    'utc_start' => '62742535200',
    'local_end' => '62758288800',
    'offset' => 32400,
    'local_start' => '62742567600'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62773984800',
    'utc_start' => '62758256400',
    'local_end' => '62774013600',
    'offset' => 28800,
    'local_start' => '62758285200'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62790310800',
    'utc_start' => '62773984800',
    'local_end' => '62790343200',
    'offset' => 32400,
    'local_start' => '62774017200'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62806039200',
    'utc_start' => '62790310800',
    'local_end' => '62806068000',
    'offset' => 28800,
    'local_start' => '62790339600'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62821760400',
    'utc_start' => '62806039200',
    'local_end' => '62821792800',
    'offset' => 32400,
    'local_start' => '62806071600'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62837488800',
    'utc_start' => '62821760400',
    'local_end' => '62837517600',
    'offset' => 28800,
    'local_start' => '62821789200'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62853210000',
    'utc_start' => '62837488800',
    'local_end' => '62853242400',
    'offset' => 32400,
    'local_start' => '62837521200'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62868938400',
    'utc_start' => '62853210000',
    'local_end' => '62868967200',
    'offset' => 28800,
    'local_start' => '62853238800'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62884659600',
    'utc_start' => '62868938400',
    'local_end' => '62884692000',
    'offset' => 32400,
    'local_start' => '62868970800'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62900388000',
    'utc_start' => '62884659600',
    'local_end' => '62900416800',
    'offset' => 28800,
    'local_start' => '62884688400'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62916109200',
    'utc_start' => '62900388000',
    'local_end' => '62916141600',
    'offset' => 32400,
    'local_start' => '62900420400'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62931837600',
    'utc_start' => '62916109200',
    'local_end' => '62931866400',
    'offset' => 28800,
    'local_start' => '62916138000'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62947558800',
    'utc_start' => '62931837600',
    'local_end' => '62947591200',
    'offset' => 32400,
    'local_start' => '62931870000'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62963892000',
    'utc_start' => '62947558800',
    'local_end' => '62963920800',
    'offset' => 28800,
    'local_start' => '62947587600'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '62979613200',
    'utc_start' => '62963892000',
    'local_end' => '62979645600',
    'offset' => 32400,
    'local_start' => '62963924400'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => '62995341600',
    'utc_start' => '62979613200',
    'local_end' => '62995370400',
    'offset' => 28800,
    'local_start' => '62979642000'
  },
  {
    'short_name' => 'ULAST',
    'utc_end' => '63011062800',
    'utc_start' => '62995341600',
    'local_end' => '63011095200',
    'offset' => 32400,
    'local_start' => '62995374000'
  },
  {
    'short_name' => 'ULAT',
    'utc_end' => $DateTime::TimeZone::INFINITY,
    'utc_start' => '63011062800',
    'offset' => 28800
  }
]
;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

__END__

=head1 NAME

DateTime::TimeZone::Asia::Ulaanbaatar - Time zone data for Asia/Ulaanbaatar

=head1 SYNOPSIS

  my $timezone = DateTime::TimeZone->new( name => 'Asia/Ulaanbaatar' );

=head1 DESCRIPTION

This module is an internal timezone definition data file used by
DateTime::TimeZone.  You do not need to use this module directly.

=cut

