#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-TimeZone
version:      0.18
version_from: lib/DateTime/TimeZone.pm
installdirs:  site
requires:
    Class::Singleton:              1.03
    Params::Validate:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
