--- #YAML:1.0
name: DateTime-TimeZone
version: 0.45
author:
  - Dave Rolsky <autarch@urth.org>
abstract: Time zone object base class and factory
license: perl
generated_by: Module::Build version 0.2703, without YAML.pm
