# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.06) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/australasia.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Australia::Darwin;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Australia::Darwin::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY,
59771575000,
DateTime::TimeZone::NEG_INFINITY,
59771606400,
31400,
0,
'LMT'
    ],
    [
59771575000,
59905494000,
59771607400,
59905526400,
32400,
0,
'CST'
    ],
    [
59905494000,
60463117860,
59905528200,
60463152060,
34200,
0,
'CST'
    ],
    [
60463117860,
61252039800,
60463155660,
61252077600,
37800,
1,
'CST'
    ],
    [
61252039800,
61291006200,
61252077600,
61291044000,
37800,
1,
'CST'
    ],
    [
61291006200,
DateTime::TimeZone::INFINITY,
61290972000,
DateTime::TimeZone::INFINITY,
34200,
0,
'CST'
    ],
];

sub _max_year { 2013 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

