# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.02) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from Perth.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Australia::Perth;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Australia::Perth::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59797757796',
    'utc_start' => DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59797785600',
    'is_dst' => 0,
    'offset' => 27804,
    'local_start' => DateTime::TimeZone::NEG_INFINITY
  },
  {
    'short_name' => 'WST',
    'utc_end' => '60463123260',
    'utc_start' => '59797757796',
    'local_end' => '60463152060',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '59797786596'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '60470298000',
    'utc_start' => '60463123260',
    'local_end' => '60470330400',
    'is_dst' => 1,
    'offset' => 32400,
    'local_start' => '60463155660'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '61252048800',
    'utc_start' => '60470298000',
    'local_end' => '61252077600',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '60470326800'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '61259562000',
    'utc_start' => '61252048800',
    'local_end' => '61259594400',
    'is_dst' => 1,
    'offset' => 32400,
    'local_start' => '61252081200'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '61275290400',
    'utc_start' => '61259562000',
    'local_end' => '61275319200',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '61259590800'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '61291011600',
    'utc_start' => '61275290400',
    'local_end' => '61291044000',
    'is_dst' => 1,
    'offset' => 32400,
    'local_start' => '61275322800'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '61299216000',
    'utc_start' => '61291011600',
    'local_end' => '61299244800',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '61291040400'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '62287725600',
    'utc_start' => '61299216000',
    'local_end' => '62287754400',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '61299244800'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '62298608400',
    'utc_start' => '62287725600',
    'local_end' => '62298640800',
    'is_dst' => 0,
    'offset' => 32400,
    'local_start' => '62287758000'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '62571981600',
    'utc_start' => '62298608400',
    'local_end' => '62572010400',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '62298637200'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '62582864400',
    'utc_start' => '62571981600',
    'local_end' => '62582896800',
    'is_dst' => 0,
    'offset' => 32400,
    'local_start' => '62572014000'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '62825997600',
    'utc_start' => '62582864400',
    'local_end' => '62826026400',
    'is_dst' => 0,
    'offset' => 28800,
    'local_start' => '62582893200'
  },
  {
    'short_name' => 'WST',
    'utc_end' => '62835066000',
    'utc_start' => '62825997600',
    'local_end' => '62835098400',
    'is_dst' => 0,
    'offset' => 32400,
    'local_start' => '62826030000'
  },
  {
    'short_name' => 'WST',
    'utc_end' => DateTime::TimeZone::INFINITY,
    'utc_start' => '62835066000',
    'local_end' => DateTime::TimeZone::INFINITY,
    'offset' => 28800,
    'local_start' => '62835037200'
  }
]
;

my $max_year = 2013;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

