# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.01) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from El_Salvador.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::America::El_Salvador;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::America::El_Salvador::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '60589403808',
    'utc_start' => $DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '60589382400',
    'offset' => -21408,
    'local_start' => '-inf'
  },
  {
    'short_name' => 'CT',
    'utc_end' => '62682703200',
    'utc_start' => '60589403808',
    'local_end' => '62682681600',
    'offset' => -21600,
    'local_start' => '60589382208'
  },
  {
    'short_name' => 'CDT',
    'utc_end' => '62695400400',
    'utc_start' => '62682703200',
    'local_end' => '62695382400',
    'offset' => -18000,
    'local_start' => '62682685200'
  },
  {
    'short_name' => 'CT',
    'utc_end' => $DateTime::TimeZone::INFINITY,
    'utc_start' => '62695400400',
    'offset' => -21600
  }
]
;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

