# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.04) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/southamerica.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::America::Guyana;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::America::Guyana::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '60405105160',
    'utc_start' => DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '60405091200',
    'is_dst' => 0,
    'offset' => -13960,
    'local_start' => DateTime::TimeZone::NEG_INFINITY
  },
  {
    'short_name' => 'GBGT',
    'utc_end' => '62021994300',
    'utc_start' => '60405105160',
    'local_end' => '62021980800',
    'is_dst' => 0,
    'offset' => -13500,
    'local_start' => '60405091660'
  },
  {
    'short_name' => 'GYT',
    'utc_end' => '62311693500',
    'utc_start' => '62021994300',
    'local_end' => '62311680000',
    'is_dst' => 0,
    'offset' => -13500,
    'local_start' => '62021980800'
  },
  {
    'short_name' => 'GYT',
    'utc_end' => '62798382000',
    'utc_start' => '62311693500',
    'local_end' => '62798371200',
    'is_dst' => 0,
    'offset' => -10800,
    'local_start' => '62311682700'
  },
  {
    'short_name' => 'GYT',
    'utc_end' => DateTime::TimeZone::INFINITY,
    'utc_start' => '62798382000',
    'local_end' => DateTime::TimeZone::INFINITY,
    'offset' => -14400,
    'local_start' => '62798396400'
  }
]
;

my $max_year = 2013;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

