# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.01) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from Montevideo.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::America::Montevideo;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::America::Montevideo::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59879015084',
    'utc_start' => DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59879001600',
    'is_dst' => 0,
    'offset' => -13484,
    'local_start' => '-inf'
  },
  {
    'short_name' => 'MMT',
    'utc_end' => '60568227884',
    'utc_start' => '59879015084',
    'local_end' => '60568214400',
    'is_dst' => 0,
    'offset' => -13484,
    'local_start' => '59879001600'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '60676140600',
    'utc_start' => '60568227884',
    'local_end' => '60676128000',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '60568215284'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '60691863600',
    'utc_start' => '60676140600',
    'local_end' => '60691852800',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '60676129800'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '60707676600',
    'utc_start' => '60691863600',
    'local_end' => '60707664000',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '60691851000'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '60723399600',
    'utc_start' => '60707676600',
    'local_end' => '60723388800',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '60707665800'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '60739212600',
    'utc_start' => '60723399600',
    'local_end' => '60739200000',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '60723387000'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '60754935600',
    'utc_start' => '60739212600',
    'local_end' => '60754924800',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '60739201800'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '60994092600',
    'utc_start' => '60754935600',
    'local_end' => '60994080000',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '60754923000'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61007394600',
    'utc_start' => '60994092600',
    'local_end' => '61007383800',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '60994081800'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61025542200',
    'utc_start' => '61007394600',
    'local_end' => '61025529600',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61007382000'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61038844200',
    'utc_start' => '61025542200',
    'local_end' => '61038833400',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61025531400'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61056991800',
    'utc_start' => '61038844200',
    'local_end' => '61056979200',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61038831600'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61070293800',
    'utc_start' => '61056991800',
    'local_end' => '61070283000',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61056981000'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61089046200',
    'utc_start' => '61070293800',
    'local_end' => '61089033600',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61070281200'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61101745200',
    'utc_start' => '61089046200',
    'local_end' => '61101734400',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61089035400'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61120495800',
    'utc_start' => '61101745200',
    'local_end' => '61120483200',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61101732600'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61133194800',
    'utc_start' => '61120495800',
    'local_end' => '61133184000',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61120485000'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61151945400',
    'utc_start' => '61133194800',
    'local_end' => '61151932800',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61133182200'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61164644400',
    'utc_start' => '61151945400',
    'local_end' => '61164633600',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61151934600'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61183395000',
    'utc_start' => '61164644400',
    'local_end' => '61183382400',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61164631800'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61196698800',
    'utc_start' => '61183395000',
    'local_end' => '61196688000',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61183384200'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61214844600',
    'utc_start' => '61196698800',
    'local_end' => '61214832000',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61196686200'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61228148400',
    'utc_start' => '61214844600',
    'local_end' => '61228137600',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61214833800'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61238863800',
    'utc_start' => '61228148400',
    'local_end' => '61238851200',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61228135800'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61252083000',
    'utc_start' => '61238863800',
    'local_end' => '61252070400',
    'is_dst' => 0,
    'offset' => -12600,
    'local_start' => '61238851200'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '61282062000',
    'utc_start' => '61252083000',
    'local_end' => '61282051200',
    'is_dst' => 1,
    'offset' => -10800,
    'local_start' => '61252072200'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '61985962800',
    'utc_start' => '61282062000',
    'local_end' => '61985952000',
    'is_dst' => 0,
    'offset' => -10800,
    'local_start' => '61282051200'
  },
  {
    'short_name' => 'UYST',
    'utc_end' => '62017408800',
    'utc_start' => '61985962800',
    'local_end' => '62017401600',
    'is_dst' => 1,
    'offset' => -7200,
    'local_start' => '61985955600'
  },
  {
    'short_name' => 'UYST',
    'utc_end' => '62035639200',
    'utc_start' => '62017408800',
    'local_end' => '62035632000',
    'is_dst' => 1,
    'offset' => -7200,
    'local_start' => '62017401600'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '62085236400',
    'utc_start' => '62035639200',
    'local_end' => '62085225600',
    'is_dst' => 0,
    'offset' => -10800,
    'local_start' => '62035628400'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '62101564200',
    'utc_start' => '62085236400',
    'local_end' => '62101555200',
    'is_dst' => 1,
    'offset' => -9000,
    'local_start' => '62085227400'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '62116772400',
    'utc_start' => '62101564200',
    'local_end' => '62116761600',
    'is_dst' => 0,
    'offset' => -10800,
    'local_start' => '62101553400'
  },
  {
    'short_name' => 'UYHST',
    'utc_end' => '62133100200',
    'utc_start' => '62116772400',
    'local_end' => '62133091200',
    'is_dst' => 1,
    'offset' => -9000,
    'local_start' => '62116763400'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '62772202800',
    'utc_start' => '62133100200',
    'local_end' => '62772192000',
    'is_dst' => 0,
    'offset' => -10800,
    'local_start' => '62133089400'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => '62792161200',
    'utc_start' => '62772202800',
    'local_end' => '62792150400',
    'is_dst' => 0,
    'offset' => -10800,
    'local_start' => '62772192000'
  },
  {
    'short_name' => 'UYST',
    'utc_end' => '62803648800',
    'utc_start' => '62792161200',
    'local_end' => '62803641600',
    'is_dst' => 1,
    'offset' => -7200,
    'local_start' => '62792154000'
  },
  {
    'short_name' => 'UYT',
    'utc_end' => DateTime::TimeZone::INFINITY,
    'utc_start' => '62803648800',
    'offset' => -10800
  }
]
;

my $max_year = 2013;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

