# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.03) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/antarctica.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Antarctica::Vostok;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Antarctica::Vostok::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'zzz',
    'utc_end' => '61755609600',
    'utc_start' => DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '61755609600',
    'is_dst' => 0,
    'offset' => 0,
    'local_start' => DateTime::TimeZone::NEG_INFINITY
  },
  {
    'short_name' => 'VOST',
    'utc_end' => DateTime::TimeZone::INFINITY,
    'utc_start' => '61755609600',
    'local_end' => DateTime::TimeZone::INFINITY,
    'offset' => 21600,
    'local_start' => '61755588000'
  }
]
;

my $max_year = 2013;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

