# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.08) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from ../../data/tz/Olson/europe.  Olson data version 2005k
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Europe::Belfast;

use strict;

use DateTime::TimeZone::Singleton;
use DateTime::TimeZone::OlsonDB;

BEGIN {
    @DateTime::TimeZone::Europe::Belfast::ISA = ( 'DateTime::TimeZone::Singleton' );
    __PACKAGE__->_load_class();
}

my $last_observance = bless( {
  'format' => 'GMT/BST',
  'gmtoff' => '0:00',
  'local_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 728659,
    'local_rd_secs' => 0,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 728659,
    'utc_rd_secs' => 0,
    'utc_year' => 1997
  }, 'DateTime' ),
  'offset_from_std' => 0,
  'offset_from_utc' => 0,
  'until' => [],
  'utc_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 728659,
    'local_rd_secs' => 0,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 728659,
    'utc_rd_secs' => 0,
    'utc_year' => 1997
  }, 'DateTime' )
}, 'DateTime::TimeZone::OlsonDB::Observance' )
;
sub last_observance { $last_observance }

my $rules = [
  DateTime::TimeZone::OlsonDB::Rule->new(
    at => '1:00u',
    from => '1996',
    in => 'Oct',
    letter => '',
    name => 'EU',
    on => 'lastSun',
    save => '0',
    to => 'max',
    type => undef
  ),
  DateTime::TimeZone::OlsonDB::Rule->new(
    at => '1:00u',
    from => '1981',
    in => 'Mar',
    letter => 'S',
    name => 'EU',
    on => 'lastSun',
    save => '1:00',
    to => 'max',
    type => undef
  ),
]
;
sub rules { $rules }


1;

