# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.01) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory
#
# Generated from Gibraltar.
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Europe::Gibraltar;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Europe::Gibraltar::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
  {
    'short_name' => 'LMT',
    'utc_end' => '59314033284',
    'utc_start' => $DateTime::TimeZone::NEG_INFINITY,
    'local_end' => '59314032000',
    'offset' => -1284,
    'local_start' => '-inf'
  },
  {
    'short_name' => '',
    'utc_end' => '60443719200',
    'utc_start' => '59314033284',
    'local_end' => '60443719200',
    'offset' => 0,
    'local_start' => '59314033284'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60455206800',
    'utc_start' => '60443719200',
    'local_end' => '60455210400',
    'offset' => 3600,
    'local_start' => '60443722800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60471540000',
    'utc_start' => '60455206800',
    'local_end' => '60471540000',
    'offset' => 0,
    'local_start' => '60455206800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60485533200',
    'utc_start' => '60471540000',
    'local_end' => '60485536800',
    'offset' => 3600,
    'local_start' => '60471543600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60501780000',
    'utc_start' => '60485533200',
    'local_end' => '60501780000',
    'offset' => 0,
    'local_start' => '60485533200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60518192400',
    'utc_start' => '60501780000',
    'local_end' => '60518196000',
    'offset' => 3600,
    'local_start' => '60501783600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60533834400',
    'utc_start' => '60518192400',
    'local_end' => '60533834400',
    'offset' => 0,
    'local_start' => '60518192400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60549642000',
    'utc_start' => '60533834400',
    'local_end' => '60549645600',
    'offset' => 3600,
    'local_start' => '60533838000'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60565284000',
    'utc_start' => '60549642000',
    'local_end' => '60565284000',
    'offset' => 0,
    'local_start' => '60549642000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60583510800',
    'utc_start' => '60565284000',
    'local_end' => '60583514400',
    'offset' => 3600,
    'local_start' => '60565287600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60597338400',
    'utc_start' => '60583510800',
    'local_end' => '60597338400',
    'offset' => 0,
    'local_start' => '60583510800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60613146000',
    'utc_start' => '60597338400',
    'local_end' => '60613149600',
    'offset' => 3600,
    'local_start' => '60597342000'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60628183200',
    'utc_start' => '60613146000',
    'local_end' => '60628183200',
    'offset' => 0,
    'local_start' => '60613146000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60645114000',
    'utc_start' => '60628183200',
    'local_end' => '60645117600',
    'offset' => 3600,
    'local_start' => '60628186800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60662052000',
    'utc_start' => '60645114000',
    'local_end' => '60662052000',
    'offset' => 0,
    'local_start' => '60645114000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60674749200',
    'utc_start' => '60662052000',
    'local_end' => '60674752800',
    'offset' => 3600,
    'local_start' => '60662055600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60692896800',
    'utc_start' => '60674749200',
    'local_end' => '60692896800',
    'offset' => 0,
    'local_start' => '60674749200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60706803600',
    'utc_start' => '60692896800',
    'local_end' => '60706807200',
    'offset' => 3600,
    'local_start' => '60692900400'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60724951200',
    'utc_start' => '60706803600',
    'local_end' => '60724951200',
    'offset' => 0,
    'local_start' => '60706803600'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60739462800',
    'utc_start' => '60724951200',
    'local_end' => '60739466400',
    'offset' => 3600,
    'local_start' => '60724954800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60756400800',
    'utc_start' => '60739462800',
    'local_end' => '60756400800',
    'offset' => 0,
    'local_start' => '60739462800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60770912400',
    'utc_start' => '60756400800',
    'local_end' => '60770916000',
    'offset' => 3600,
    'local_start' => '60756404400'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60787245600',
    'utc_start' => '60770912400',
    'local_end' => '60787245600',
    'offset' => 0,
    'local_start' => '60770912400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60802362000',
    'utc_start' => '60787245600',
    'local_end' => '60802365600',
    'offset' => 3600,
    'local_start' => '60787249200'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60819904800',
    'utc_start' => '60802362000',
    'local_end' => '60819904800',
    'offset' => 0,
    'local_start' => '60802362000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60834416400',
    'utc_start' => '60819904800',
    'local_end' => '60834420000',
    'offset' => 3600,
    'local_start' => '60819908400'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60851354400',
    'utc_start' => '60834416400',
    'local_end' => '60851354400',
    'offset' => 0,
    'local_start' => '60834416400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60865866000',
    'utc_start' => '60851354400',
    'local_end' => '60865869600',
    'offset' => 3600,
    'local_start' => '60851358000'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60882199200',
    'utc_start' => '60865866000',
    'local_end' => '60882199200',
    'offset' => 0,
    'local_start' => '60865866000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60897315600',
    'utc_start' => '60882199200',
    'local_end' => '60897319200',
    'offset' => 3600,
    'local_start' => '60882202800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60914253600',
    'utc_start' => '60897315600',
    'local_end' => '60914253600',
    'offset' => 0,
    'local_start' => '60897315600'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60928765200',
    'utc_start' => '60914253600',
    'local_end' => '60928768800',
    'offset' => 3600,
    'local_start' => '60914257200'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60945703200',
    'utc_start' => '60928765200',
    'local_end' => '60945703200',
    'offset' => 0,
    'local_start' => '60928765200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60960214800',
    'utc_start' => '60945703200',
    'local_end' => '60960218400',
    'offset' => 3600,
    'local_start' => '60945706800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '60976548000',
    'utc_start' => '60960214800',
    'local_end' => '60976548000',
    'offset' => 0,
    'local_start' => '60960214800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '60992269200',
    'utc_start' => '60976548000',
    'local_end' => '60992272800',
    'offset' => 3600,
    'local_start' => '60976551600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61009207200',
    'utc_start' => '60992269200',
    'local_end' => '61009207200',
    'offset' => 0,
    'local_start' => '60992269200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61023718800',
    'utc_start' => '61009207200',
    'local_end' => '61023722400',
    'offset' => 3600,
    'local_start' => '61009210800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61040052000',
    'utc_start' => '61023718800',
    'local_end' => '61040052000',
    'offset' => 0,
    'local_start' => '61023718800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61055168400',
    'utc_start' => '61040052000',
    'local_end' => '61055172000',
    'offset' => 3600,
    'local_start' => '61040055600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61072106400',
    'utc_start' => '61055168400',
    'local_end' => '61072106400',
    'offset' => 0,
    'local_start' => '61055168400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61086618000',
    'utc_start' => '61072106400',
    'local_end' => '61086621600',
    'offset' => 3600,
    'local_start' => '61072110000'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61103556000',
    'utc_start' => '61086618000',
    'local_end' => '61103556000',
    'offset' => 0,
    'local_start' => '61086618000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61118067600',
    'utc_start' => '61103556000',
    'local_end' => '61118071200',
    'offset' => 3600,
    'local_start' => '61103559600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61134400800',
    'utc_start' => '61118067600',
    'local_end' => '61134400800',
    'offset' => 0,
    'local_start' => '61118067600'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61149517200',
    'utc_start' => '61134400800',
    'local_end' => '61149520800',
    'offset' => 3600,
    'local_start' => '61134404400'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61166455200',
    'utc_start' => '61149517200',
    'local_end' => '61166455200',
    'offset' => 0,
    'local_start' => '61149517200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61185200400',
    'utc_start' => '61166455200',
    'local_end' => '61185204000',
    'offset' => 3600,
    'local_start' => '61166458800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61193671200',
    'utc_start' => '61185200400',
    'local_end' => '61193671200',
    'offset' => 0,
    'local_start' => '61185200400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61231161600',
    'utc_start' => '61193671200',
    'local_end' => '61231165200',
    'offset' => 3600,
    'local_start' => '61193674800'
  },
  {
    'short_name' => 'BDST',
    'utc_end' => '61239625200',
    'utc_start' => '61231161600',
    'local_end' => '61239632400',
    'offset' => 7200,
    'local_start' => '61231168800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61260192000',
    'utc_start' => '61239625200',
    'local_end' => '61260195600',
    'offset' => 3600,
    'local_start' => '61239628800'
  },
  {
    'short_name' => 'BDST',
    'utc_end' => '61271074800',
    'utc_start' => '61260192000',
    'local_end' => '61271082000',
    'offset' => 7200,
    'local_start' => '61260199200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61291641600',
    'utc_start' => '61271074800',
    'local_end' => '61291645200',
    'offset' => 3600,
    'local_start' => '61271078400'
  },
  {
    'short_name' => 'BDST',
    'utc_end' => '61303129200',
    'utc_start' => '61291641600',
    'local_end' => '61303136400',
    'offset' => 7200,
    'local_start' => '61291648800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61323091200',
    'utc_start' => '61303129200',
    'local_end' => '61323094800',
    'offset' => 3600,
    'local_start' => '61303132800'
  },
  {
    'short_name' => 'BDST',
    'utc_end' => '61337602800',
    'utc_start' => '61323091200',
    'local_end' => '61337610000',
    'offset' => 7200,
    'local_start' => '61323098400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61354627200',
    'utc_start' => '61337602800',
    'local_end' => '61354630800',
    'offset' => 3600,
    'local_start' => '61337606400'
  },
  {
    'short_name' => 'BDST',
    'utc_end' => '61363609200',
    'utc_start' => '61354627200',
    'local_end' => '61363616400',
    'offset' => 7200,
    'local_start' => '61354634400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61370874000',
    'utc_start' => '61363609200',
    'local_end' => '61370877600',
    'offset' => 3600,
    'local_start' => '61363612800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61387207200',
    'utc_start' => '61370874000',
    'local_end' => '61387207200',
    'offset' => 0,
    'local_start' => '61370874000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61402323600',
    'utc_start' => '61387207200',
    'local_end' => '61402327200',
    'offset' => 3600,
    'local_start' => '61387210800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61416237600',
    'utc_start' => '61402323600',
    'local_end' => '61416237600',
    'offset' => 0,
    'local_start' => '61402323600'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61418649600',
    'utc_start' => '61416237600',
    'local_end' => '61418653200',
    'offset' => 3600,
    'local_start' => '61416241200'
  },
  {
    'short_name' => 'BDST',
    'utc_end' => '61428927600',
    'utc_start' => '61418649600',
    'local_end' => '61428934800',
    'offset' => 7200,
    'local_start' => '61418656800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61436192400',
    'utc_start' => '61428927600',
    'local_end' => '61436196000',
    'offset' => 3600,
    'local_start' => '61428931200'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61447687200',
    'utc_start' => '61436192400',
    'local_end' => '61447687200',
    'offset' => 0,
    'local_start' => '61436192400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61467642000',
    'utc_start' => '61447687200',
    'local_end' => '61467645600',
    'offset' => 3600,
    'local_start' => '61447690800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61480951200',
    'utc_start' => '61467642000',
    'local_end' => '61480951200',
    'offset' => 0,
    'local_start' => '61467642000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61499091600',
    'utc_start' => '61480951200',
    'local_end' => '61499095200',
    'offset' => 3600,
    'local_start' => '61480954800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61513610400',
    'utc_start' => '61499091600',
    'local_end' => '61513610400',
    'offset' => 0,
    'local_start' => '61499091600'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61529936400',
    'utc_start' => '61513610400',
    'local_end' => '61529940000',
    'offset' => 3600,
    'local_start' => '61513614000'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61545060000',
    'utc_start' => '61529936400',
    'local_end' => '61545060000',
    'offset' => 0,
    'local_start' => '61529936400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61561386000',
    'utc_start' => '61545060000',
    'local_end' => '61561389600',
    'offset' => 3600,
    'local_start' => '61545063600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61577114400',
    'utc_start' => '61561386000',
    'local_end' => '61577114400',
    'offset' => 0,
    'local_start' => '61561386000'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61593440400',
    'utc_start' => '61577114400',
    'local_end' => '61593444000',
    'offset' => 3600,
    'local_start' => '61577118000'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61608564000',
    'utc_start' => '61593440400',
    'local_end' => '61608564000',
    'offset' => 0,
    'local_start' => '61593440400'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61623075600',
    'utc_start' => '61608564000',
    'local_end' => '61623079200',
    'offset' => 3600,
    'local_start' => '61608567600'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61639408800',
    'utc_start' => '61623075600',
    'local_end' => '61639408800',
    'offset' => 0,
    'local_start' => '61623075600'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61654525200',
    'utc_start' => '61639408800',
    'local_end' => '61654528800',
    'offset' => 3600,
    'local_start' => '61639412400'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61671463200',
    'utc_start' => '61654525200',
    'local_end' => '61671463200',
    'offset' => 0,
    'local_start' => '61654525200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61685974800',
    'utc_start' => '61671463200',
    'local_end' => '61685978400',
    'offset' => 3600,
    'local_start' => '61671466800'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61703517600',
    'utc_start' => '61685974800',
    'local_end' => '61703517600',
    'offset' => 0,
    'local_start' => '61685974800'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61718029200',
    'utc_start' => '61703517600',
    'local_end' => '61718032800',
    'offset' => 3600,
    'local_start' => '61703521200'
  },
  {
    'short_name' => 'GMT',
    'utc_end' => '61734362400',
    'utc_start' => '61718029200',
    'local_end' => '61734362400',
    'offset' => 0,
    'local_start' => '61718029200'
  },
  {
    'short_name' => 'BST',
    'utc_end' => '61734358800',
    'utc_start' => '61734362400',
    'local_end' => '61734362400',
    'offset' => 3600,
    'local_start' => '61734366000'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62514370800',
    'utc_start' => '61734358800',
    'local_end' => '62514374400',
    'offset' => 3600,
    'local_start' => '61734362400'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62521804800',
    'utc_start' => '62514370800',
    'local_end' => '62521808400',
    'offset' => 3600,
    'local_start' => '62514374400'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62537526000',
    'utc_start' => '62521804800',
    'local_end' => '62537533200',
    'offset' => 7200,
    'local_start' => '62521812000'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62553254400',
    'utc_start' => '62537526000',
    'local_end' => '62553258000',
    'offset' => 3600,
    'local_start' => '62537529600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62568975600',
    'utc_start' => '62553254400',
    'local_end' => '62568982800',
    'offset' => 7200,
    'local_start' => '62553261600'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62584704000',
    'utc_start' => '62568975600',
    'local_end' => '62584707600',
    'offset' => 3600,
    'local_start' => '62568979200'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62601030000',
    'utc_start' => '62584704000',
    'local_end' => '62601037200',
    'offset' => 7200,
    'local_start' => '62584711200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62616758400',
    'utc_start' => '62601030000',
    'local_end' => '62616762000',
    'offset' => 3600,
    'local_start' => '62601033600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62632479600',
    'utc_start' => '62616758400',
    'local_end' => '62632486800',
    'offset' => 7200,
    'local_start' => '62616765600'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62648208000',
    'utc_start' => '62632479600',
    'local_end' => '62648211600',
    'offset' => 3600,
    'local_start' => '62632483200'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62663929200',
    'utc_start' => '62648208000',
    'local_end' => '62663936400',
    'offset' => 7200,
    'local_start' => '62648215200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62679657600',
    'utc_start' => '62663929200',
    'local_end' => '62679661200',
    'offset' => 3600,
    'local_start' => '62663932800'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62695378800',
    'utc_start' => '62679657600',
    'local_end' => '62695386000',
    'offset' => 7200,
    'local_start' => '62679664800'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62711107200',
    'utc_start' => '62695378800',
    'local_end' => '62711110800',
    'offset' => 3600,
    'local_start' => '62695382400'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62726828400',
    'utc_start' => '62711107200',
    'local_end' => '62726835600',
    'offset' => 7200,
    'local_start' => '62711114400'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62742556800',
    'utc_start' => '62726828400',
    'local_end' => '62742560400',
    'offset' => 3600,
    'local_start' => '62726832000'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62758278000',
    'utc_start' => '62742556800',
    'local_end' => '62758285200',
    'offset' => 7200,
    'local_start' => '62742564000'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62774006400',
    'utc_start' => '62758278000',
    'local_end' => '62774010000',
    'offset' => 3600,
    'local_start' => '62758281600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62790332400',
    'utc_start' => '62774006400',
    'local_end' => '62790339600',
    'offset' => 7200,
    'local_start' => '62774013600'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62806060800',
    'utc_start' => '62790332400',
    'local_end' => '62806064400',
    'offset' => 3600,
    'local_start' => '62790336000'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62821782000',
    'utc_start' => '62806060800',
    'local_end' => '62821789200',
    'offset' => 7200,
    'local_start' => '62806068000'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62837510400',
    'utc_start' => '62821782000',
    'local_end' => '62837514000',
    'offset' => 3600,
    'local_start' => '62821785600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62853231600',
    'utc_start' => '62837510400',
    'local_end' => '62853238800',
    'offset' => 7200,
    'local_start' => '62837517600'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62868960000',
    'utc_start' => '62853231600',
    'local_end' => '62868963600',
    'offset' => 3600,
    'local_start' => '62853235200'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62884681200',
    'utc_start' => '62868960000',
    'local_end' => '62884688400',
    'offset' => 7200,
    'local_start' => '62868967200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62900409600',
    'utc_start' => '62884681200',
    'local_end' => '62900413200',
    'offset' => 3600,
    'local_start' => '62884684800'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62916130800',
    'utc_start' => '62900409600',
    'local_end' => '62916138000',
    'offset' => 7200,
    'local_start' => '62900416800'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62931859200',
    'utc_start' => '62916130800',
    'local_end' => '62931862800',
    'offset' => 3600,
    'local_start' => '62916134400'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62963910000',
    'utc_start' => '62931859200',
    'local_end' => '62963917200',
    'offset' => 7200,
    'local_start' => '62931866400'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '62982054000',
    'utc_start' => '62963910000',
    'local_end' => '62982061200',
    'offset' => 7200,
    'local_start' => '62963917200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '62995363200',
    'utc_start' => '62982054000',
    'local_end' => '62995366800',
    'offset' => 3600,
    'local_start' => '62982057600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63013503600',
    'utc_start' => '62995363200',
    'local_end' => '63013510800',
    'offset' => 7200,
    'local_start' => '62995370400'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63026812800',
    'utc_start' => '63013503600',
    'local_end' => '63026816400',
    'offset' => 3600,
    'local_start' => '63013507200'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63044953200',
    'utc_start' => '63026812800',
    'local_end' => '63044960400',
    'offset' => 7200,
    'local_start' => '63026820000'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63058262400',
    'utc_start' => '63044953200',
    'local_end' => '63058266000',
    'offset' => 3600,
    'local_start' => '63044956800'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63077007600',
    'utc_start' => '63058262400',
    'local_end' => '63077014800',
    'offset' => 7200,
    'local_start' => '63058269600'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63089712000',
    'utc_start' => '63077007600',
    'local_end' => '63089715600',
    'offset' => 3600,
    'local_start' => '63077011200'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63108457200',
    'utc_start' => '63089712000',
    'local_end' => '63108464400',
    'offset' => 7200,
    'local_start' => '63089719200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63121161600',
    'utc_start' => '63108457200',
    'local_end' => '63121165200',
    'offset' => 3600,
    'local_start' => '63108460800'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63139906800',
    'utc_start' => '63121161600',
    'local_end' => '63139914000',
    'offset' => 7200,
    'local_start' => '63121168800'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63153216000',
    'utc_start' => '63139906800',
    'local_end' => '63153219600',
    'offset' => 3600,
    'local_start' => '63139910400'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63171356400',
    'utc_start' => '63153216000',
    'local_end' => '63171363600',
    'offset' => 7200,
    'local_start' => '63153223200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63184665600',
    'utc_start' => '63171356400',
    'local_end' => '63184669200',
    'offset' => 3600,
    'local_start' => '63171360000'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63202806000',
    'utc_start' => '63184665600',
    'local_end' => '63202813200',
    'offset' => 7200,
    'local_start' => '63184672800'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63216115200',
    'utc_start' => '63202806000',
    'local_end' => '63216118800',
    'offset' => 3600,
    'local_start' => '63202809600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63234860400',
    'utc_start' => '63216115200',
    'local_end' => '63234867600',
    'offset' => 7200,
    'local_start' => '63216122400'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63247564800',
    'utc_start' => '63234860400',
    'local_end' => '63247568400',
    'offset' => 3600,
    'local_start' => '63234864000'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63266310000',
    'utc_start' => '63247564800',
    'local_end' => '63266317200',
    'offset' => 7200,
    'local_start' => '63247572000'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63279014400',
    'utc_start' => '63266310000',
    'local_end' => '63279018000',
    'offset' => 3600,
    'local_start' => '63266313600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63297759600',
    'utc_start' => '63279014400',
    'local_end' => '63297766800',
    'offset' => 7200,
    'local_start' => '63279021600'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63310464000',
    'utc_start' => '63297759600',
    'local_end' => '63310467600',
    'offset' => 3600,
    'local_start' => '63297763200'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63329209200',
    'utc_start' => '63310464000',
    'local_end' => '63329216400',
    'offset' => 7200,
    'local_start' => '63310471200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63342518400',
    'utc_start' => '63329209200',
    'local_end' => '63342522000',
    'offset' => 3600,
    'local_start' => '63329212800'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63360658800',
    'utc_start' => '63342518400',
    'local_end' => '63360666000',
    'offset' => 7200,
    'local_start' => '63342525600'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63373968000',
    'utc_start' => '63360658800',
    'local_end' => '63373971600',
    'offset' => 3600,
    'local_start' => '63360662400'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63392108400',
    'utc_start' => '63373968000',
    'local_end' => '63392115600',
    'offset' => 7200,
    'local_start' => '63373975200'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63405417600',
    'utc_start' => '63392108400',
    'local_end' => '63405421200',
    'offset' => 3600,
    'local_start' => '63392112000'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63424162800',
    'utc_start' => '63405417600',
    'local_end' => '63424170000',
    'offset' => 7200,
    'local_start' => '63405424800'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63436867200',
    'utc_start' => '63424162800',
    'local_end' => '63436870800',
    'offset' => 3600,
    'local_start' => '63424166400'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63455612400',
    'utc_start' => '63436867200',
    'local_end' => '63455619600',
    'offset' => 7200,
    'local_start' => '63436874400'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63468316800',
    'utc_start' => '63455612400',
    'local_end' => '63468320400',
    'offset' => 3600,
    'local_start' => '63455616000'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63487062000',
    'utc_start' => '63468316800',
    'local_end' => '63487069200',
    'offset' => 7200,
    'local_start' => '63468324000'
  },
  {
    'short_name' => 'CET',
    'utc_end' => '63500371200',
    'utc_start' => '63487062000',
    'local_end' => '63500374800',
    'offset' => 3600,
    'local_start' => '63487065600'
  },
  {
    'short_name' => 'CEST',
    'utc_end' => '63518511600',
    'utc_start' => '63500371200',
    'local_end' => '63518518800',
    'offset' => 7200,
    'local_start' => '63500378400'
  }
]
;

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}

my $rules = [
  bless( {
    'letter' => '',
    'on' => 'lastSun',
    'save' => '0',
    'to' => 'max',
    'from' => '1996',
    'in' => 'Oct',
    'at' => '1:00u',
    'type' => undef,
    'offset' => 0
  }, 'DateTime::TimeZone::OlsonDB::Rule' ),
  bless( {
    'letter' => 'S',
    'on' => 'lastSun',
    'save' => '1:00',
    'to' => 'max',
    'from' => '1981',
    'in' => 'Mar',
    'at' => '1:00u',
    'type' => undef,
    'offset' => 3600
  }, 'DateTime::TimeZone::OlsonDB::Rule' )
]
;
my $last_observance = bless( {
  'until' => undef,
  'format' => 'CE%sT',
  'gmtoff' => '1:00',
  'rules' => 'EU',
  'offset' => 3600,
  'start' => bless( {
    'local_rd_secs' => 0,
    'c' => {
      'hour' => 0,
      'minute' => 0,
      'second' => 0,
      'month' => 1,
      'day_of_year' => 1,
      'day_of_week' => 5,
      'day' => 1,
      'year' => 1982
    },
    'local_rd_days' => 723546,
    'language' => bless( {
      'month_numbers' => {},
      'am_pm' => [
        'AM',
        'PM'
      ],
      'ordinal_suffixes' => [],
      'month_abbreviations' => [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec'
      ],
      'day_abbreviations' => [
        'Mon',
        'Tue',
        'Wed',
        'Thu',
        'Fri',
        'Sat',
        'Sun'
      ],
      'month_names' => [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December'
      ],
      'day_numbers' => {},
      'day_names' => [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday'
      ]
    }, 'DateTime::Language::English' ),
    'tz' => bless( {}, 'DateTime::TimeZone::UTC' ),
    'utc_rd_secs' => 0,
    'utc_rd_days' => 723546
  }, 'DateTime' )
}, 'DateTime::TimeZone::OlsonDB::Observance' )
;

sub _generate_spans_until_match
{
    my $self = shift;
    my $dt = shift;

    my @changes;
    foreach my $rule (@$rules)
    {
        my $year = $dt->year;

        my $next = $rule->date_for_year( $year, 3600 );

        # don't bother with changes we've seen already
        next if $next->{utc}->utc_rd_as_seconds < $self->{max_span}{utc_end};

        push @changes,
            DateTime::TimeZone::OlsonDB::Change->new
                ( start_date => $next->{local},
                  short_name =>
                  sprintf( $last_observance->format, $rule->letter ),
                  observance => $last_observance,
                  rule       => $rule,
                );

        next unless $next->{utc} < $dt;

        $next = $rule->date_for_year( $year + 1, 3600 );

        push @changes,
            DateTime::TimeZone::OlsonDB::Change->new
                ( start_date => $next->{local},
                  short_name =>
                  sprintf( $last_observance->format, $rule->letter ),
                  observance => $last_observance,
                  rule       => $rule,
                );
    }

    my @sorted = sort { $a->start_date <=> $b->start_date } @changes;

    my $seconds = $dt->utc_rd_as_seconds;
    my $match;

    for ( my $x = 1; $x < @sorted; $x++ )
    {
        my $last_offset =
            $x == 1 ? $self->{max_span}{offset} : $changes[ $x - 2 ]->offset;

        my $span =
            DateTime::TimeZone::OlsonDB::Change::two_changes_as_span
                ( @sorted[ $x - 1, $x ], $last_offset );

        $self->{tree}->insert( { utc   => [ $span->{utc_start},   $span->{utc_end} ],
                                 local => [ $span->{local_start}, $span->{local_end} ],
                               },
                               $span );

        $match = $span
            if $seconds >= $span->{utc_start} && $seconds < $span->{utc_end};
    }

    $self->{max_span} = $self->{tree}->max->val;

    return $match;
}


1;

__END__

=head1 NAME

DateTime::TimeZone::Europe::Gibraltar - Time zone data for Europe/Gibraltar

=head1 SYNOPSIS

  my $timezone = DateTime::TimeZone->new( name => 'Europe/Gibraltar' );

=head1 DESCRIPTION

This module is an internal timezone definition data file used by
DateTime::TimeZone.  You do not need to use this module directly.

=cut

